apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      imagePullSecrets:
      - name: nexus-registry-secret
      containers:
      - name: boardgame
        image: 192.168.176.128:8082/boardgame:latest
        ports:
        - containerPort: 8080
